# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75c8c9ce3237fe9dc42a5a16c7b867e7369cd350ce40e18f2b059e05f24eeaaad4ecd4e3e3b6d97f63ccbda348c625f34fe47c78e7b5813c92cb340f41565253

test:
  secret_key_base: 085d7dffe8b2689fdccfb81071447d0d2a75a8e0397952b400c00c24ac5461ab408b3ce49ccf42c54eb8fdcb889a05f91f25b830298276e996ed12013db957b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
